name: carousel_pro
description: A Flutter Carousel Slider widget. Support Network and Asset Images. You can modify the UI according your design easily.
version: 1.0.0
author: David Cruz (davthecoder) <info@davthecoder.com>
homepage: https://github.com/davthecodercom/flutter-carousel-pro

environment:
  sdk: '^3.0.0'
  flutter: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
